# 作業

- 作業目標 : iris (dataset.load_iris()) 資料嘗試跑 kmeans (可以測試不同的群數 , init 等)

In [40]:
from sklearn import datasets

iris = datasets.load_iris()
X = iris.data
y = iris.target

In [42]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

### 載入 相關套件 並 執行 kmean 實驗 ...

- 實驗測試不同的群數
- 實驗測試不同的初始值
- 呈現結果

In [24]:
from sklearn.cluster import KMeans
import numpy as np

In [53]:
#實驗測試不同的群數
estimators = [('k_means_8', KMeans(n_clusters=8)),
              ('k_means_3', KMeans(n_clusters=3)),
#實驗測試不同的初始值            
              ('init_1',KMeans(n_clusters=3,init="random")),
             ('init_2',KMeans(n_clusters=3,init="random"))]

In [54]:
fignum=1
title=["8 clusters","3 clusters","init_1","init_2"]
for name, est in estimators:
    est.fit(X)
    est.labels_
    est.cluster_centers_
    print(name,"\n",est.labels_,"\n",est.cluster_centers_,"\n")

k_means_8 
 [1 6 6 6 1 1 6 1 6 6 1 6 6 6 1 1 1 1 1 1 1 1 6 1 6 6 1 1 1 6 6 1 1 1 6 6 1
 1 6 1 1 6 6 1 1 6 1 6 1 6 7 7 7 4 7 4 7 3 7 4 3 4 4 7 4 7 4 4 0 4 0 4 0 7
 7 7 7 7 7 3 3 3 4 0 4 7 7 7 4 4 4 7 4 3 4 4 4 7 3 4 5 0 5 5 5 2 4 2 5 2 5
 0 5 0 0 5 5 2 2 0 5 0 2 0 5 2 0 0 5 5 2 2 5 0 0 2 5 5 0 5 5 5 0 5 5 5 0 5
 5 0] 
 [[6.03684211 2.70526316 5.         1.77894737]
 [5.24285714 3.66785714 1.5        0.28214286]
 [7.54       3.15       6.39       2.09      ]
 [5.24285714 2.37142857 3.44285714 1.02857143]
 [5.62857143 2.72380952 4.13333333 1.2952381 ]
 [6.61666667 3.07916667 5.5625     2.1375    ]
 [4.70454545 3.12272727 1.41363636 0.2       ]
 [6.44210526 2.97894737 4.59473684 1.43157895]] 

k_means_3 
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 0 0 0 0 2 0 0 0 0
 0 0 2 2 0 0 0 0 2 0 2 0 2 0 0 2 2 0 0 0 0 0 2 0 0 0 0 2 0 0 0 2